# Generated by Django 4.0.2 on 2022-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(verbose_name='Tier')),
                ('type', models.CharField(max_length=120, verbose_name='Type')),
                ('nation', models.CharField(max_length=120, verbose_name='Nation')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('small_icon', models.CharField(default=None, max_length=400, verbose_name='Small_icon')),
                ('modernization_1', models.CharField(default=None, max_length=255, verbose_name='Modernization 1')),
                ('modernization_2', models.CharField(default=None, max_length=255, verbose_name='Modernization 2')),
                ('modernization_3', models.CharField(default=None, max_length=255, verbose_name='Modernization 3')),
                ('modernization_4', models.CharField(default='---', max_length=255, verbose_name='Modernization 4')),
                ('modernization_5', models.CharField(default='---', max_length=255, verbose_name='Modernization 5')),
                ('flag', models.ImageField(blank=True, upload_to='flags/')),
                ('type_icon', models.ImageField(blank=True, upload_to='type_icons/')),
            ],
            options={
                'verbose_name': 'Танк',
                'verbose_name_plural': 'Танки',
            },
        ),
    ]
