# Generated by Django 4.0.2 on 2022-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanksbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='heroku_flag',
            field=models.CharField(max_length=400, null=True, verbose_name='Heroku_flag'),
        ),
        migrations.AddField(
            model_name='tank',
            name='heroku_type',
            field=models.CharField(max_length=400, null=True, verbose_name='Heroku_type'),
        ),
    ]
